import { Download, GitBranch, Layers3, Maximize2, Minus, Move, Plus, RotateCcw, Search, ShieldCheck, SlidersHorizontal } from "lucide-react";
import { PointerEvent, useEffect, useMemo, useRef, useState } from "react";
import { api, type Analysis, type Artifact, type BusbarEvidence, type ConductorEvidence, type Drawing, type ElectricalGraph, type Feeder, type JunctionEvidence, type PhysicalConnection, type PhysicalGraph, type SymbolEvidence, type TextEvidence } from "./lib/api";

const label = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
type Props = { drawing: Drawing; analysis: Analysis; artifacts: Artifact[]; texts: TextEvidence[]; symbols: SymbolEvidence[]; conductors: ConductorEvidence[]; buses: BusbarEvidence[]; junctions: JunctionEvidence[]; physicalGraph: PhysicalGraph | null; onTexts: (items: TextEvidence[]) => void; onSymbols: (items: SymbolEvidence[]) => void; onGraph: (graph: PhysicalGraph) => void; onJunctions: (items: JunctionEvidence[]) => void };
type Panel = "trace" | "review" | "scenario" | "export" | "validation";
type Mode = "original" | "reconstructed" | "graph";

export function TextWorkspace(props: Props) {
  const { drawing, analysis, artifacts, texts, symbols, conductors, buses, junctions, physicalGraph, onTexts, onSymbols, onGraph, onJunctions } = props;
  const [artifactType, setArtifactType] = useState("display");
  const [mode, setMode] = useState<Mode>("original");
  const [panel, setPanel] = useState<Panel>("trace");
  const [electrical, setElectrical] = useState<ElectricalGraph | null>(null);
  const [trace, setTrace] = useState<Feeder | null>(null);
  const [selectedConnection, setSelectedConnection] = useState<PhysicalConnection | null>(null);
  const [selectedJunction, setSelectedJunction] = useState<JunctionEvidence | null>(null);
  const [selectedSymbol, setSelectedSymbol] = useState<SymbolEvidence | null>(null);
  const [selectedText, setSelectedText] = useState<TextEvidence | null>(null);
  const [query, setQuery] = useState("");
  const [layers, setLayers] = useState(false);
  const [showText, setShowText] = useState(true);
  const [showSymbols, setShowSymbols] = useState(true);
  const [showConductors, setShowConductors] = useState(true);
  const [showJunctions, setShowJunctions] = useState(true);
  const [zoom, setZoom] = useState(1);
  const [offset, setOffset] = useState({ x: 0, y: 0 });
  const [scenario, setScenario] = useState<Record<string, string>>({});
  const [scenarioResult, setScenarioResult] = useState<{ feeders: { equipment_id: string; feeder_id: string; resolution: string }[] } | null>(null);
  const [manualFrom, setManualFrom] = useState<string | null>(null);
  const drag = useRef<{ x: number; y: number } | null>(null);
  const reloadElectrical = () => api.electricalGraph(analysis.id).then(setElectrical).catch(() => setElectrical(null));
  useEffect(() => { api.electricalGraph(analysis.id).then(setElectrical).catch(() => setElectrical(null)); }, [analysis.id]);
  const artifact = useMemo(() => artifacts.find((item) => item.type === artifactType) ?? artifacts.find((item) => item.type === "display") ?? artifacts[0], [artifacts, artifactType]);
  const page = artifact?.metadata.page ?? 1;
  const pageEdges = physicalGraph?.edges.filter((item) => item.page === page && item.review_status !== "rejected") ?? [];
  const pageJunctions = junctions.filter((item) => item.page === page);
  const pageConductors = conductors.filter((item) => item.page === page);
  const pageBuses = buses.filter((item) => item.page === page);
  const focus = (box: [number, number, number, number]) => { setZoom(1.55); setOffset({ x: (0.5 - (box[0] + box[2]) / 2) * 480, y: (0.5 - (box[1] + box[3]) / 2) * 300 }); };
  const clearSelection = () => { setSelectedConnection(null); setSelectedJunction(null); setSelectedSymbol(null); setSelectedText(null); };
  const chooseTrace = async (feeder: Feeder) => { setTrace(await api.feederTrace(feeder.id)); setPanel("trace"); setMode("original"); };
  const saveText = async (action: "accept" | "reject" | "unknown" | "edit", value?: string, textType?: string) => { if (!selectedText) return; const updated = action === "edit" ? await api.updateText(selectedText.id, value ?? selectedText.normalized_text, textType ?? selectedText.text_type) : await api.reviewText(selectedText.id, action); onTexts(texts.map((item) => item.id === updated.id ? updated : item)); setSelectedText(updated); reloadElectrical(); };
  const reviewSymbol = async (action: "accept" | "reject" | "verify", kind?: string) => { if (!selectedSymbol) return; const updated = kind ? await api.updateSymbol(selectedSymbol.id, kind) : await api.reviewSymbol(selectedSymbol.id, action); onSymbols(symbols.map((item) => item.id === updated.id ? updated : item)); setSelectedSymbol(updated); reloadElectrical(); };
  const reviewConnection = async (action: "accept" | "reject" | "verify") => { if (!selectedConnection || !physicalGraph) return; const updated = await api.reviewConnection(selectedConnection.id, action); onGraph({ ...physicalGraph, edges: physicalGraph.edges.map((item) => item.id === updated.id ? updated : item) }); setSelectedConnection(updated); reloadElectrical(); };
  const reviewCrossing = async (decision: "connected" | "unconnected" | "unable_to_determine") => { if (!selectedJunction) return; const updated = await api.decideCrossing(selectedJunction.id, decision); onJunctions(junctions.map((item) => item.id === updated.id ? { ...item, ...updated } : item)); reloadElectrical(); };
  const selectManualTerminal = async (terminalId: string) => { if (manualFrom === null || !physicalGraph) return; if (!manualFrom) { setManualFrom(terminalId); return; } if (manualFrom === terminalId) { setManualFrom(""); return; } const edge = await api.addManualConnection(analysis.id, drawing.id, manualFrom, terminalId); onGraph({ ...physicalGraph, edges: [...physicalGraph.edges, edge] }); setManualFrom(null); reloadElectrical(); };
  const searchedFeeders = electrical?.feeders.filter((item) => item.feeder_id.toLowerCase().includes(query.toLowerCase())) ?? [];
  const traceConnections = new Set(trace?.path?.connection_path ?? []);
  return <>
    <div className="context workspace-context">
      <div><p className="eyebrow">Electrical intelligence workspace</p><h1>{drawing.original_filename}</h1><p>{electrical ? `${electrical.health.sources} source candidates · ${electrical.health.resolved_paths} / ${electrical.health.feeders} resolved feeder paths · ${electrical.health.review_items} review items` : "Loading persisted source-to-feeder intelligence"}</p></div>
      <div className="toolbar"><button title="Zoom out" onClick={() => setZoom((value) => Math.max(.25, value - .1))}><Minus /></button><span>{Math.round(zoom * 100)}%</span><button title="Zoom in" onClick={() => setZoom((value) => Math.min(3, value + .1))}><Plus /></button><button title="Fit drawing" onClick={() => { setZoom(1); setOffset({ x: 0, y: 0 }); }}><Maximize2 /> Fit</button><button title="Reset view" onClick={() => { setZoom(1); setOffset({ x: 0, y: 0 }); }}><RotateCcw /></button><button title="Add manual physical connection" className={manualFrom !== null ? "active" : ""} onClick={() => { setMode("graph"); setManualFrom(manualFrom === null ? "" : null); }}><GitBranch /> Add edge</button><button title="Layers" onClick={() => setLayers(!layers)}><Layers3 /></button></div>
    </div>
    <div className="workspace-tabs" role="tablist"><button className={mode === "original" ? "active" : ""} onClick={() => setMode("original")}>Original</button><button className={mode === "reconstructed" ? "active" : ""} onClick={() => setMode("reconstructed")}>Reconstructed</button><button className={mode === "graph" ? "active" : ""} onClick={() => setMode("graph")}>Graph</button></div>
    <div className="workspace-body m5-workspace">
      <section className="viewport" onWheel={(event) => { event.preventDefault(); setZoom((value) => Math.min(3, Math.max(.25, value * (event.deltaY < 0 ? 1.12 : .89)))); }} onPointerMove={(event: PointerEvent) => { if (!drag.current) return; setOffset((value) => ({ x: value.x + event.clientX - drag.current!.x, y: value.y + event.clientY - drag.current!.y })); drag.current = { x: event.clientX, y: event.clientY }; }} onPointerUp={() => drag.current = null} onPointerLeave={() => drag.current = null}>
        {mode === "original" && <div className="sheet text-sheet" style={{ transform: `translate(${offset.x}px, ${offset.y}px) scale(${zoom})` }} onPointerDown={(event) => { drag.current = { x: event.clientX, y: event.clientY }; }}><img draggable="false" src={artifact ? api.artifactUrl(artifact.id) : undefined} alt="Uploaded electrical drawing" /><TopologyOverlay conductors={pageConductors} buses={pageBuses} edges={pageEdges} junctions={pageJunctions} selectedConnection={selectedConnection?.id} traceConnections={traceConnections} showConductors={showConductors} showJunctions={showJunctions} onConnection={(edge) => { clearSelection(); setSelectedConnection(edge); }} onJunction={(item) => { clearSelection(); setSelectedJunction(item); focus([item.position[0] - .04, item.position[1] - .04, item.position[0] + .04, item.position[1] + .04]); }} />{showText && texts.filter((item) => item.page === page).map((item) => <Overlay key={item.id} kind="text" bbox={item.bbox_normalized} selected={selectedText?.id === item.id} review={item.review_status === "pending"} name={`Text ${item.normalized_text}`} onClick={() => { clearSelection(); setSelectedText(item); focus(item.bbox_normalized); }} />)}{showSymbols && symbols.filter((item) => item.page === page && item.review_status !== "rejected").map((item) => <Overlay key={item.id} kind="symbol" bbox={item.bbox_normalized} selected={selectedSymbol?.id === item.id} review={item.review_status === "pending"} name={`Symbol ${label(item.predicted_class)}`} onClick={() => { clearSelection(); setSelectedSymbol(item); focus(item.bbox_normalized); }} />)}</div>}
        {mode === "reconstructed" && <object className="reconstructed-sheet" data={api.reconstructionUrl(analysis.id)} type="image/svg+xml" aria-label="Reconstructed digital SLD" />}
        {mode === "graph" && <ElectricalGraphView graph={physicalGraph} electrical={electrical} trace={trace} onTrace={chooseTrace} manualFrom={manualFrom} onNode={selectManualTerminal} />}
        <div className="canvas-hint"><Move size={13} /> Scroll to zoom · drag to pan</div>
        {mode === "original" && <div className="artifact-switch">{["display", "grayscale", "contrast", "binary", "line_emphasized"].filter((wanted) => artifacts.some((item) => item.type === wanted)).map((item) => <button className={artifactType === item ? "active" : ""} key={item} onClick={() => setArtifactType(item)}>{label(item)}</button>)}</div>}
        {layers && <div className="layers-popover"><strong>Evidence layers</strong><Layer checked={showText} name="Text" count={texts.length} onChange={setShowText} /><Layer checked={showSymbols} name="Symbols" count={symbols.length} onChange={setShowSymbols} /><Layer checked={showConductors} name="Conductors" count={pageConductors.length} onChange={setShowConductors} /><Layer checked={showJunctions} name="Junctions" count={pageJunctions.length} onChange={setShowJunctions} /></div>}
      </section>
      <aside className="inspector electrical-inspector">
        <nav className="intelligence-nav"><button className={panel === "trace" ? "active" : ""} onClick={() => setPanel("trace")}><GitBranch /> Trace</button><button className={panel === "review" ? "active" : ""} onClick={() => setPanel("review")}><ShieldCheck /> Review</button><button className={panel === "scenario" ? "active" : ""} onClick={() => setPanel("scenario")}><SlidersHorizontal /> Scenario</button><button className={panel === "validation" ? "active" : ""} onClick={() => setPanel("validation")}>Validation</button><button className={panel === "export" ? "active" : ""} onClick={() => setPanel("export")}><Download /> Export</button></nav>
        {selectedConnection ? <ConnectionInspector edge={selectedConnection} onReview={reviewConnection} /> : selectedJunction ? <JunctionInspector junction={selectedJunction} onReview={reviewCrossing} /> : selectedSymbol ? <SymbolInspector symbol={selectedSymbol} texts={texts} onReview={reviewSymbol} /> : selectedText ? <TextInspector text={selectedText} onSave={saveText} /> : <ElectricalPanel panel={panel} electrical={electrical} trace={trace} query={query} onQuery={setQuery} feeders={searchedFeeders} onTrace={chooseTrace} onInspect={(id) => { const edge = physicalGraph?.edges.find((item) => item.id === id); if (edge) { clearSelection(); setSelectedConnection(edge); setMode("original"); } }} analysisId={analysis.id} scenario={scenario} onScenario={setScenario} scenarioResult={scenarioResult} onScenarioResult={setScenarioResult} reload={reloadElectrical} />}
      </aside>
    </div>
  </>;
}

function ElectricalPanel({ panel, electrical, trace, query, onQuery, feeders, onTrace, onInspect, analysisId, scenario, onScenario, scenarioResult, onScenarioResult, reload }: { panel: Panel; electrical: ElectricalGraph | null; trace: Feeder | null; query: string; onQuery: (value: string) => void; feeders: Feeder[]; onTrace: (item: Feeder) => void; onInspect: (id: string) => void; analysisId: string; scenario: Record<string, string>; onScenario: (value: Record<string, string>) => void; scenarioResult: { feeders: { equipment_id: string; feeder_id: string; resolution: string }[] } | null; onScenarioResult: (value: { feeders: { equipment_id: string; feeder_id: string; resolution: string }[] } | null) => void; reload: () => void }) {
  if (!electrical) return <><p className="eyebrow">Electrical intelligence</p><h2>Awaiting graph evidence</h2><p className="inspector-note">Source and feeder reasoning appears after persisted physical topology is available.</p></>;
  if (panel === "trace") return <><p className="eyebrow">Trace & explain</p><h2>{trace?.feeder_id ?? "Find a feeder"}</h2><div className="text-search"><Search size={14} /><input aria-label="Search feeder / equipment" value={query} placeholder="Search FDR-07" onChange={(event) => onQuery(event.target.value)} /></div>{trace ? <TraceCard trace={trace} labels={electrical.equipment_labels} /> : <div className="trace-list">{feeders.map((item) => <button key={item.id} onClick={() => onTrace(item)}><strong>{item.feeder_id}</strong><small>{item.resolution} · {Math.round(item.confidence * 100)}%</small></button>)}</div>}<p className="inspector-note">Path confidence uses a geometric mean and exposes its weakest physical connection. UNKNOWN switching state remains explicit.</p></>;
  if (panel === "review") return <><p className="eyebrow">Review center</p><h2>Topology consequence</h2><div className="review-list">{electrical.review_issues.map((item) => <article key={item.id} className={`priority-${item.priority.toLowerCase()}`}><small>{item.priority}</small><strong>Possible physical connection</strong><span>{Math.round(item.confidence * 100)}% connectivity · {item.affected_feeders.length} affected feeder(s)</span><button className="quiet" onClick={() => onInspect(item.target_id)}>Inspect</button><button className="quiet" onClick={() => api.reviewIssue(item.id, "accept").then(reload)}>Accept</button><button className="text-button" onClick={() => api.reviewIssue(item.id, "reject").then(reload)}>Reject</button></article>)}</div><p className="inspector-note">Items are ranked by uncertainty × topology impact, never raw detection confidence alone.</p></>;
  if (panel === "scenario") return <><p className="eyebrow">Scenario mode</p><h2>Switch-state connectivity</h2><div className="switch-list">{electrical.switch_states.map((item) => <label key={item.equipment_id}>{item.equipment_id}<select value={scenario[item.equipment_id] ?? item.state} onChange={(event) => onScenario({ ...scenario, [item.equipment_id]: event.target.value })}><option value="unknown">Unknown</option><option value="closed">Closed</option><option value="open">Open</option></select></label>)}</div><button className="primary" onClick={() => api.simulate(analysisId, scenario).then(onScenarioResult)}>Simulate connectivity</button>{Object.keys(scenario).length > 0 && <button className="quiet" onClick={() => Promise.all(Object.entries(scenario).map(([equipmentId, state]) => api.setSwitchState(analysisId, equipmentId, state as "open" | "closed" | "unknown"))).then(reload)}>Save reviewed switch states</button>}{scenarioResult && <div className="scenario-result"><strong>Temporary result</strong>{scenarioResult.feeders.map((item) => <span key={item.equipment_id}>{item.feeder_id}: {item.resolution}</span>)}</div>}<p className="inspector-note">Simulation is temporary. Saving records an engineer-reviewed switch state and recomputes only electrical graph views.</p></>;
  if (panel === "validation") return <ValidationPanel electrical={electrical} />;
  return <><p className="eyebrow">Export center</p><h2>Validated network package</h2><div className="export-counts"><span>{electrical.feeders.length} feeders</span><span>{electrical.sources.length} sources</span><span>{electrical.review_issues.length} review items</span></div><a className="primary" href={api.exportJson(analysisId)} target="_blank" rel="noreferrer">Export JSON</a><a className="quiet" href={api.exportBundle(analysisId)}>Export full ZIP package</a><p className="inspector-note">Exports include confidence, review status, and provenance. They never include local file paths.</p></>;
}

function TraceCard({ trace, labels }: { trace: Feeder; labels: Record<string, string> }) { const path = trace.path; const display = (id: string | null | undefined, fallback: string) => id ? labels[id] ?? id : fallback; return <div className="trace-card"><Property label="Source" value={display(path?.source_equipment_id, "Unresolved")} /><Property label="Source bus" value={display(trace.source_bus_equipment_id, "Unknown")} /><Property label="Destination" value={display(trace.destination_equipment_id, "Unknown")} /><Property label="Voltage" value={trace.voltage ?? "Unknown"} /><Property label="Path confidence" value={`${Math.round((path?.confidence ?? 0) * 100)}%`} /><Property label="Weakest link" value={path?.weakest_connection_id ? `${path.weakest_connection_id} · ${Math.round((path.weakest_connection_confidence ?? 0) * 100)}%` : "None"} /><div className="path-sequence">{path?.equipment_path.map((item) => display(item, item)).join(" → ") || "Physical topology break; source not assigned."}</div>{path?.uncertainty_flags.map((item) => <small className="warning" key={item}>{label(item)}</small>)}</div>; }
function ValidationPanel({ electrical }: { electrical: ElectricalGraph }) { return <><p className="eyebrow">Validation lab</p><h2>{electrical.health.status}</h2><div className="health-summary"><span>Sources {electrical.health.sources}</span><span>Feeders {electrical.health.feeders}</span><span>Resolved {electrical.health.resolved_paths}</span><span>Review {electrical.health.review_items}</span></div><div className="validation-list">{electrical.validation.map((item) => <article key={item.id}><strong>{label(item.code)}</strong><small>{item.severity} · {item.message}</small></article>)}</div><p className="inspector-note">These are structural and semantic consistency checks, not power-flow or IEC certification.</p></>; }
function ElectricalGraphView({ graph, electrical, trace, onTrace, manualFrom, onNode }: { graph: PhysicalGraph | null; electrical: ElectricalGraph | null; trace: Feeder | null; onTrace: (item: Feeder) => void; manualFrom: string | null; onNode: (id: string) => void }) { if (!graph) return <div className="empty"><strong>No physical graph evidence</strong></div>; const nodes = new Map(graph.nodes.map((item) => [item.id, item])); const traced = new Set(trace?.path?.connection_path ?? []); return <div className="electrical-graph"><p className="eyebrow">Operational / physical graph</p>{manualFrom !== null && <p className="inspector-note">{manualFrom ? "Select the second terminal to create a verified physical connection." : "Select the first terminal for the manual physical connection."}</p>}<svg viewBox="0 0 1000 1000" preserveAspectRatio="none">{graph.edges.filter((item) => item.review_status !== "rejected").map((edge) => { const left = nodes.get(edge.from_node_id), right = nodes.get(edge.to_node_id); return left && right ? <line key={edge.id} x1={left.position[0] * 1000} y1={left.position[1] * 1000} x2={right.position[0] * 1000} y2={right.position[1] * 1000} className={traced.has(edge.id) ? "graph-edge traced" : "graph-edge"} /> : null; })}{graph.nodes.map((node) => <g key={node.id} className={`graph-node ${manualFrom === node.id ? "selected" : ""}`} transform={`translate(${node.position[0] * 1000} ${node.position[1] * 1000})`} onClick={() => onNode(node.id)}><circle r="24" /><text y="4">{node.label.slice(0, 6).toUpperCase()}</text></g>)}</svg><div className="trace-list">{electrical?.feeders.map((item) => <button key={item.id} onClick={() => onTrace(item)}>{item.feeder_id}</button>)}</div></div>; }
function TopologyOverlay({ conductors, buses, edges, junctions, selectedConnection, traceConnections, showConductors, showJunctions, onConnection, onJunction }: { conductors: ConductorEvidence[]; buses: BusbarEvidence[]; edges: PhysicalConnection[]; junctions: JunctionEvidence[]; selectedConnection?: string; traceConnections: Set<string>; showConductors: boolean; showJunctions: boolean; onConnection: (item: PhysicalConnection) => void; onJunction: (item: JunctionEvidence) => void }) { const points = (polyline: [number, number][]) => polyline.map(([x, y]) => `${x * 1000},${y * 1000}`).join(" "); return <svg className="topology-overlay" viewBox="0 0 1000 1000" preserveAspectRatio="none">{showConductors && conductors.map((item) => <polyline key={item.id} points={points(item.polyline)} className="conductor-trace" />)}{buses.map((item) => <polyline key={item.id} points={points(item.polyline)} className="bus-trace" />)}{edges.map((item) => <polyline key={item.id} points={points(item.polyline)} className={`physical-edge ${selectedConnection === item.id ? "selected" : ""} ${traceConnections.has(item.id) ? "traced" : ""} ${item.review_status === "pending" ? "review" : ""}`} onClick={(event) => { event.stopPropagation(); onConnection(item); }} />)}{showJunctions && junctions.map((item) => <circle key={item.id} cx={item.position[0] * 1000} cy={item.position[1] * 1000} r="7" className={`junction-marker ${item.kind}`} onClick={(event) => { event.stopPropagation(); onJunction(item); }} />)}</svg>; }
function Overlay({ bbox, kind, selected, review, name, onClick }: { bbox: [number, number, number, number]; kind: "text" | "symbol"; selected: boolean; review: boolean; name: string; onClick: () => void }) { const [x1, y1, x2, y2] = bbox; return <button aria-label={name} className={`${kind}-region ${selected ? "selected" : ""} ${review ? "review" : ""}`} style={{ left: `${x1 * 100}%`, top: `${y1 * 100}%`, width: `${(x2 - x1) * 100}%`, height: `${(y2 - y1) * 100}%` }} onClick={(event) => { event.stopPropagation(); onClick(); }} />; }
function Layer({ checked, name, count, onChange }: { checked: boolean; name: string; count: number; onChange: (value: boolean) => void }) { return <label><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} />{name}<small>{count}</small></label>; }
function TextInspector({ text, onSave }: { text: TextEvidence; onSave: (action: "accept" | "reject" | "unknown" | "edit", value?: string, type?: string) => void }) { const [value, setValue] = useState(text.engineer_value ?? text.normalized_text); const [type, setType] = useState(text.engineer_text_type ?? text.text_type); return <><p className="eyebrow">Text evidence</p><h2>{text.engineer_value ?? text.normalized_text}</h2><Property label="Raw OCR" value={text.raw_text} /><label className="text-edit">Normalized<input value={value} onChange={(event) => setValue(event.target.value)} /></label><label className="text-edit">Type<select value={type} onChange={(event) => setType(event.target.value)}><option value="equipment_id">Equipment ID</option><option value="feeder_id">Feeder ID</option><option value="bus_id">Bus ID</option><option value="unknown">Unknown</option></select></label><div className="review-actions"><button className="quiet" onClick={() => onSave("edit", value, type)}>Save edit</button><button className="primary" onClick={() => onSave("accept")}>Accept</button><button className="text-button" onClick={() => onSave("reject")}>Reject</button></div></>; }
function SymbolInspector({ symbol, texts, onReview }: { symbol: SymbolEvidence; texts: TextEvidence[]; onReview: (action: "accept" | "reject" | "verify", type?: string) => void }) { const linked = texts.filter((item) => symbol.associations.some((association) => association.text_evidence_id === item.id)); return <><p className="eyebrow">Component candidate</p><h2>{label(symbol.predicted_class)}</h2><Property label="Detection" value={symbol.confidence == null ? "Not model-derived" : `${Math.round(symbol.confidence * 100)}%`} /><Property label="Text match" value={linked.length ? linked.map((item) => item.normalized_text).join(", ") : "Unassigned"} /><label className="text-edit">Class<select value={symbol.predicted_class} onChange={(event) => onReview("accept", event.target.value)}>{["power_transformer", "circuit_breaker", "disconnector", "current_transformer", "potential_transformer", "busbar", "feeder_terminal", "load", "energy_source", "bus_coupler"].map((item) => <option key={item} value={item}>{label(item)}</option>)}</select></label><div className="review-actions"><button className="primary" onClick={() => onReview("verify")}>Verify</button><button className="quiet" onClick={() => onReview("accept")}>Accept</button><button className="text-button" onClick={() => onReview("reject")}>Reject</button></div></>; }
function ConnectionInspector({ edge, onReview }: { edge: PhysicalConnection; onReview: (action: "accept" | "reject" | "verify") => void }) { return <><p className="eyebrow">Physical connection</p><h2>Connection evidence</h2><Property label="Confidence" value={`${Math.round(edge.confidence * 100)}% connectivity`} /><Property label="Provenance" value={edge.provenance} /><div className="review-actions"><button className="primary" onClick={() => onReview("verify")}>Verify</button><button className="quiet" onClick={() => onReview("accept")}>Accept</button><button className="text-button" onClick={() => onReview("reject")}>Reject</button></div></>; }
function JunctionInspector({ junction, onReview }: { junction: JunctionEvidence; onReview: (action: "connected" | "unconnected" | "unable_to_determine") => void }) { return <><p className="eyebrow">Crossing review</p><h2>{label(junction.kind)}</h2><Property label="Evidence" value={`${Math.round(junction.confidence * 100)}% local geometry`} /><div className="review-actions"><button className="primary" onClick={() => onReview("connected")}>Connected</button><button className="quiet" onClick={() => onReview("unconnected")}>Not connected</button><button className="text-button" onClick={() => onReview("unable_to_determine")}>Unable to determine</button></div></>; }
function Property({ label, value }: { label: string; value: string }) { return <div className="property"><span>{label}</span><strong>{value}</strong></div>; }
